name: Promote Image
run-name: "Promote Image: ${{ github.event.release.tag_name }}"

on:
  release:
    types: [published]

jobs:
  promote:
    uses: themotleyfool/cloudops-shared-workflows/.github/workflows/promote_image.yaml@v1
    with:
      app: next-js-template
      releaseTag: ${{ github.event.release.tag_name }}
      slackChannel: "#<SLACK_CHANNEL>"
    secrets: inherit